###
GET http://localhost:3000/api/employees

###
POST http://localhost:3000/api/employees
Content-Type: application/json

{
    "name": "foo",
    "position": "lider",
    "office": "programer",
    "salary": "200"
}

###
GET http://localhost:3000/api/employees/60210f3f3380462120196794


###
DELETE http://localhost:3000/api/employees/60210f3f3380462120196794

###
PUT http://localhost:3000/api/employees/602112cf0f7a151f1cfbe01f
Content-Type: application/json

{
    "salary": 400
}

