###
GET http://localhost:3000/api/todo

###
GET http://localhost:3000/api/todo/606dcf8cad54d13b6c3d5a3b

###
GET http://localhost:3000/api/todo/CompletTasks

###
GET http://localhost:3000/api/todo/EndWithJS

###
GET http://localhost:3000/api/todo/MastStartNComplet

###
GET http://localhost:3000/api/todo/PremNoComplOfYearAgo

###
GET http://localhost:3000/api/todo/Special

###
PUT http://localhost:3000/api/todo/SetFalseAllMaterTasks

###
PUT http://localhost:3000/api/todo/SetTrueFirstReactTasks

###
DELETE http://localhost:3000/api/todo/606dea458bf31f301c2327da

###
DELETE http://localhost:3000/api/todo/DeleteNewTasks
